#
#   docker build -  -t test-x10_rest < Dockerfile_working_git
#   docker images  
# Ensure correct device name is used!
#   docker run --rm --device=/dev/ttyUSB0 -p 1234:1234  test-x10_rest

# Alpine
#
#FROM python:3.8-slim
# git does not work with slim
FROM python:3.8


RUN git clone https://github.com/clach04/x10_rest.git && \
    cd x10_rest && \
    pip install -r requirements.txt


CMD [ "python3", "x10_rest/x10_rest.py" ]

